### PR TITLE
Tap language

### PR DESCRIPTION
**Pull request by Cerabbite**
# Todo
- [ ] Clean up repo
- [x] Make readme with installation instructions
- [x] Finish language

### CODE REVIEW

**Review by jntrnr — CHANGES_REQUESTED** [review]
please only touch files in your directory. Looks like you're deleting other files as well.

**Comment by Cerabbite** [comment]
@jntrnr Which files have I deleted? I only know of the TEAM file since I work alone, do I need to put that back?

**Comment by jntrnr** [comment]
@Cerabbite - yup, you'll need to put back this directory: https://github.com/langjam/jam0004/pull/15/files#diff-72391ae214a694030421035e06739384b6e48d18f807b186a257059ee327d3ca

**Comment by Cerabbite** [comment]
Ok i'll do

**Pull request merged**
